module.exports = [
  { number: 1,   name: 'Hydrogen',      symbol: 'H',   mass: 1.008,    category: 'nonmetal' },
  { number: 2,   name: 'Helium',        symbol: 'He',  mass: 4.003,    category: 'noble gas' },
  { number: 3,   name: 'Lithium',       symbol: 'Li',  mass: 6.941,    category: 'alkali metal' },
  { number: 4,   name: 'Beryllium',     symbol: 'Be',  mass: 9.012,    category: 'alkaline earth metal' },
  { number: 5,   name: 'Boron',         symbol: 'B',   mass: 10.811,   category: 'metalloid' },
  { number: 6,   name: 'Carbon',        symbol: 'C',   mass: 12.011,   category: 'nonmetal' },
  { number: 7,   name: 'Nitrogen',      symbol: 'N',   mass: 14.007,   category: 'nonmetal' },
  { number: 8,   name: 'Oxygen',        symbol: 'O',   mass: 15.999,   category: 'nonmetal' },
  { number: 9,   name: 'Fluorine',      symbol: 'F',   mass: 18.998,   category: 'halogen' },
  { number: 10,  name: 'Neon',          symbol: 'Ne',  mass: 20.180,   category: 'noble gas' },
  { number: 11,  name: 'Sodium',        symbol: 'Na',  mass: 22.990,   category: 'alkali metal' },
  { number: 12,  name: 'Magnesium',     symbol: 'Mg',  mass: 24.305,   category: 'alkaline earth metal' },
  { number: 13,  name: 'Aluminum',      symbol: 'Al',  mass: 26.982,   category: 'post-transition metal' },
  { number: 14,  name: 'Silicon',       symbol: 'Si',  mass: 28.086,   category: 'metalloid' },
  { number: 15,  name: 'Phosphorus',    symbol: 'P',   mass: 30.974,   category: 'nonmetal' },
  { number: 16,  name: 'Sulfur',        symbol: 'S',   mass: 32.065,   category: 'nonmetal' },
  { number: 17,  name: 'Chlorine',      symbol: 'Cl',  mass: 35.453,   category: 'halogen' },
  { number: 18,  name: 'Argon',         symbol: 'Ar',  mass: 39.948,   category: 'noble gas' },
  { number: 19,  name: 'Potassium',     symbol: 'K',   mass: 39.098,   category: 'alkali metal' },
  { number: 20,  name: 'Calcium',       symbol: 'Ca',  mass: 40.078,   category: 'alkaline earth metal' },
  { number: 21,  name: 'Scandium',      symbol: 'Sc',  mass: 44.956,   category: 'transition metal' },
  { number: 22,  name: 'Titanium',      symbol: 'Ti',  mass: 47.867,   category: 'transition metal' },
  { number: 23,  name: 'Vanadium',      symbol: 'V',   mass: 50.942,   category: 'transition metal' },
  { number: 24,  name: 'Chromium',      symbol: 'Cr',  mass: 51.996,   category: 'transition metal' },
  { number: 25,  name: 'Manganese',     symbol: 'Mn',  mass: 54.938,   category: 'transition metal' },
  { number: 26,  name: 'Iron',          symbol: 'Fe',  mass: 55.845,   category: 'transition metal' },
  { number: 27,  name: 'Cobalt',        symbol: 'Co',  mass: 58.933,   category: 'transition metal' },
  { number: 28,  name: 'Nickel',        symbol: 'Ni',  mass: 58.693,   category: 'transition metal' },
  { number: 29,  name: 'Copper',        symbol: 'Cu',  mass: 63.546,   category: 'transition metal' },
  { number: 30,  name: 'Zinc',          symbol: 'Zn',  mass: 65.38,    category: 'transition metal' },
  { number: 31,  name: 'Gallium',       symbol: 'Ga',  mass: 69.723,   category: 'post-transition metal' },
  { number: 32,  name: 'Germanium',     symbol: 'Ge',  mass: 72.630,   category: 'metalloid' },
  { number: 33,  name: 'Arsenic',       symbol: 'As',  mass: 74.922,   category: 'metalloid' },
  { number: 34,  name: 'Selenium',      symbol: 'Se',  mass: 78.971,   category: 'nonmetal' },
  { number: 35,  name: 'Bromine',       symbol: 'Br',  mass: 79.904,   category: 'halogen' },
  { number: 36,  name: 'Krypton',       symbol: 'Kr',  mass: 83.798,   category: 'noble gas' },
  { number: 37,  name: 'Rubidium',      symbol: 'Rb',  mass: 85.468,   category: 'alkali metal' },
  { number: 38,  name: 'Strontium',     symbol: 'Sr',  mass: 87.62,    category: 'alkaline earth metal' },
  { number: 39,  name: 'Yttrium',       symbol: 'Y',   mass: 88.906,   category: 'transition metal' },
  { number: 40,  name: 'Zirconium',     symbol: 'Zr',  mass: 91.224,   category: 'transition metal' },
  { number: 41,  name: 'Niobium',       symbol: 'Nb',  mass: 92.906,   category: 'transition metal' },
  { number: 42,  name: 'Molybdenum',    symbol: 'Mo',  mass: 95.96,    category: 'transition metal' },
  { number: 43,  name: 'Technetium',    symbol: 'Tc',  mass: 98.000,   category: 'transition metal' },
  { number: 44,  name: 'Ruthenium',     symbol: 'Ru',  mass: 101.07,   category: 'transition metal' },
  { number: 45,  name: 'Rhodium',       symbol: 'Rh',  mass: 102.906,  category: 'transition metal' },
  { number: 46,  name: 'Palladium',     symbol: 'Pd',  mass: 106.42,   category: 'transition metal' },
  { number: 47,  name: 'Silver',        symbol: 'Ag',  mass: 107.868,  category: 'transition metal' },
  { number: 48,  name: 'Cadmium',       symbol: 'Cd',  mass: 112.411,  category: 'transition metal' },
  { number: 49,  name: 'Indium',        symbol: 'In',  mass: 114.818,  category: 'post-transition metal' },
  { number: 50,  name: 'Tin',           symbol: 'Sn',  mass: 118.710,  category: 'post-transition metal' },
  { number: 51,  name: 'Antimony',      symbol: 'Sb',  mass: 121.760,  category: 'metalloid' },
  { number: 52,  name: 'Tellurium',     symbol: 'Te',  mass: 127.60,   category: 'metalloid' },
  { number: 53,  name: 'Iodine',        symbol: 'I',   mass: 126.904,  category: 'halogen' },
  { number: 54,  name: 'Xenon',         symbol: 'Xe',  mass: 131.293,  category: 'noble gas' },
  { number: 55,  name: 'Cesium',        symbol: 'Cs',  mass: 132.905,  category: 'alkali metal' },
  { number: 56,  name: 'Barium',        symbol: 'Ba',  mass: 137.327,  category: 'alkaline earth metal' },
  { number: 57,  name: 'Lanthanum',     symbol: 'La',  mass: 138.905,  category: 'lanthanide' },
  { number: 58,  name: 'Cerium',        symbol: 'Ce',  mass: 140.116,  category: 'lanthanide' },
  { number: 59,  name: 'Praseodymium',  symbol: 'Pr',  mass: 140.908,  category: 'lanthanide' },
  { number: 60,  name: 'Neodymium',     symbol: 'Nd',  mass: 144.242,  category: 'lanthanide' },
  { number: 61,  name: 'Promethium',    symbol: 'Pm',  mass: 145.000,  category: 'lanthanide' },
  { number: 62,  name: 'Samarium',      symbol: 'Sm',  mass: 150.36,   category: 'lanthanide' },
  { number: 63,  name: 'Europium',      symbol: 'Eu',  mass: 151.964,  category: 'lanthanide' },
  { number: 64,  name: 'Gadolinium',    symbol: 'Gd',  mass: 157.25,   category: 'lanthanide' },
  { number: 65,  name: 'Terbium',       symbol: 'Tb',  mass: 158.925,  category: 'lanthanide' },
  { number: 66,  name: 'Dysprosium',    symbol: 'Dy',  mass: 162.500,  category: 'lanthanide' },
  { number: 67,  name: 'Holmium',       symbol: 'Ho',  mass: 164.930,  category: 'lanthanide' },
  { number: 68,  name: 'Erbium',        symbol: 'Er',  mass: 167.259,  category: 'lanthanide' },
  { number: 69,  name: 'Thulium',       symbol: 'Tm',  mass: 168.934,  category: 'lanthanide' },
  { number: 70,  name: 'Ytterbium',     symbol: 'Yb',  mass: 173.054,  category: 'lanthanide' },
  { number: 71,  name: 'Lutetium',      symbol: 'Lu',  mass: 174.967,  category: 'lanthanide' },
  { number: 72,  name: 'Hafnium',       symbol: 'Hf',  mass: 178.49,   category: 'transition metal' },
  { number: 73,  name: 'Tantalum',      symbol: 'Ta',  mass: 180.948,  category: 'transition metal' },
  { number: 74,  name: 'Tungsten',      symbol: 'W',   mass: 183.84,   category: 'transition metal' },
  { number: 75,  name: 'Rhenium',       symbol: 'Re',  mass: 186.207,  category: 'transition metal' },
  { number: 76,  name: 'Osmium',        symbol: 'Os',  mass: 190.23,   category: 'transition metal' },
  { number: 77,  name: 'Iridium',       symbol: 'Ir',  mass: 192.217,  category: 'transition metal' },
  { number: 78,  name: 'Platinum',      symbol: 'Pt',  mass: 195.084,  category: 'transition metal' },
  { number: 79,  name: 'Gold',          symbol: 'Au',  mass: 196.967,  category: 'transition metal' },
  { number: 80,  name: 'Mercury',       symbol: 'Hg',  mass: 200.59,   category: 'transition metal' },
  { number: 81,  name: 'Thallium',      symbol: 'Tl',  mass: 204.383,  category: 'post-transition metal' },
  { number: 82,  name: 'Lead',          symbol: 'Pb',  mass: 207.2,    category: 'post-transition metal' },
  { number: 83,  name: 'Bismuth',       symbol: 'Bi',  mass: 208.980,  category: 'post-transition metal' },
  { number: 84,  name: 'Polonium',      symbol: 'Po',  mass: 209.000,  category: 'post-transition metal' },
  { number: 85,  name: 'Astatine',      symbol: 'At',  mass: 210.000,  category: 'halogen' },
  { number: 86,  name: 'Radon',         symbol: 'Rn',  mass: 222.000,  category: 'noble gas' },
  { number: 87,  name: 'Francium',      symbol: 'Fr',  mass: 223.000,  category: 'alkali metal' },
  { number: 88,  name: 'Radium',        symbol: 'Ra',  mass: 226.000,  category: 'alkaline earth metal' },
  { number: 89,  name: 'Actinium',      symbol: 'Ac',  mass: 227.000,  category: 'actinide' },
  { number: 90,  name: 'Thorium',       symbol: 'Th',  mass: 232.038,  category: 'actinide' },
  { number: 91,  name: 'Protactinium',  symbol: 'Pa',  mass: 231.036,  category: 'actinide' },
  { number: 92,  name: 'Uranium',       symbol: 'U',   mass: 238.029,  category: 'actinide' },
  { number: 93,  name: 'Neptunium',     symbol: 'Np',  mass: 237.000,  category: 'actinide' },
  { number: 94,  name: 'Plutonium',     symbol: 'Pu',  mass: 244.000,  category: 'actinide' },
  { number: 95,  name: 'Americium',     symbol: 'Am',  mass: 243.000,  category: 'actinide' },
  { number: 96,  name: 'Curium',        symbol: 'Cm',  mass: 247.000,  category: 'actinide' },
  { number: 97,  name: 'Berkelium',     symbol: 'Bk',  mass: 247.000,  category: 'actinide' },
  { number: 98,  name: 'Californium',   symbol: 'Cf',  mass: 251.000,  category: 'actinide' },
  { number: 99,  name: 'Einsteinium',   symbol: 'Es',  mass: 252.000,  category: 'actinide' },
  { number: 100, name: 'Fermium',       symbol: 'Fm',  mass: 257.000,  category: 'actinide' },
  { number: 101, name: 'Mendelevium',   symbol: 'Md',  mass: 258.000,  category: 'actinide' },
  { number: 102, name: 'Nobelium',      symbol: 'No',  mass: 259.000,  category: 'actinide' },
  { number: 103, name: 'Lawrencium',    symbol: 'Lr',  mass: 262.000,  category: 'actinide' },
  { number: 104, name: 'Rutherfordium', symbol: 'Rf',  mass: 267.000,  category: 'transition metal' },
  { number: 105, name: 'Dubnium',       symbol: 'Db',  mass: 270.000,  category: 'transition metal' },
  { number: 106, name: 'Seaborgium',    symbol: 'Sg',  mass: 271.000,  category: 'transition metal' },
  { number: 107, name: 'Bohrium',       symbol: 'Bh',  mass: 274.000,  category: 'transition metal' },
  { number: 108, name: 'Hassium',       symbol: 'Hs',  mass: 277.000,  category: 'transition metal' },
  { number: 109, name: 'Meitnerium',    symbol: 'Mt',  mass: 278.000,  category: 'transition metal' },
  { number: 110, name: 'Darmstadtium',  symbol: 'Ds',  mass: 281.000,  category: 'transition metal' },
  { number: 111, name: 'Roentgenium',   symbol: 'Rg',  mass: 282.000,  category: 'transition metal' },
  { number: 112, name: 'Copernicium',   symbol: 'Cn',  mass: 285.000,  category: 'transition metal' },
  { number: 113, name: 'Nihonium',      symbol: 'Nh',  mass: 286.000,  category: 'post-transition metal' },
  { number: 114, name: 'Flerovium',     symbol: 'Fl',  mass: 289.000,  category: 'post-transition metal' },
  { number: 115, name: 'Moscovium',     symbol: 'Mc',  mass: 290.000,  category: 'post-transition metal' },
  { number: 116, name: 'Livermorium',   symbol: 'Lv',  mass: 293.000,  category: 'post-transition metal' },
  { number: 117, name: 'Tennessine',    symbol: 'Ts',  mass: 294.000,  category: 'halogen' },
  { number: 118, name: 'Oganesson',     symbol: 'Og',  mass: 294.000,  category: 'noble gas' },
];
